<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
    </PropertyGroup>
    <PropertyGroup>
        <PackageId>Orchid.Garmin.FIT.Sdk</PackageId>
        <Authors>Garmin International, Inc.;Anthony Barclay</Authors>
        <Company>Garmin International, Inc.</Company>
        <PackageDescription>FIT C# SDK with additional fields</PackageDescription>
		<RepositoryUrl>https://github.com/anthome-uk/fit-csharp-sdk</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE.txt" Pack="true" PackagePath="" />
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="Cookbook\**" />
        <Compile Remove="Cookbook\**" />
        <EmbeddedResource Remove="Cookbook\**" />
        <None Remove="Cookbook\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="Examples\**" />
        <Compile Remove="Examples\**" />
        <EmbeddedResource Remove="Examples\**" />
        <None Remove="Examples\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="plugins\**" />
        <Compile Remove="plugins\**" />
        <EmbeddedResource Remove="plugins\**" />
        <None Remove="plugins\**" />
    </ItemGroup>

</Project>